package com.row49382.test_util;

public class ExpectedTestJson {

    public static final String GITHUB_USER_RESPONSE_JSON = """
            {
                 "login": "octocat",
                 "id": 583231,
                 "node_id": "MDQ6VXNlcjU4MzIzMQ==",
                 "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
                 "gravatar_id": "",
                 "url": "https://api.github.com/users/octocat",
                 "html_url": "https://github.com/octocat",
                 "followers_url": "https://api.github.com/users/octocat/followers",
                 "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                 "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                 "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                 "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                 "organizations_url": "https://api.github.com/users/octocat/orgs",
                 "repos_url": "https://api.github.com/users/octocat/repos",
                 "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                 "received_events_url": "https://api.github.com/users/octocat/received_events",
                 "type": "User",
                 "user_view_type": "public",
                 "site_admin": false,
                 "name": "The Octocat",
                 "company": "@github",
                 "blog": "https://github.blog",
                 "location": "San Francisco",
                 "email": null,
                 "hireable": null,
                 "bio": null,
                 "twitter_username": null,
                 "public_repos": 8,
                 "public_gists": 8,
                 "followers": 17367,
                 "following": 9,
                 "created_at": "2011-01-25T18:44:36Z",
                 "updated_at": "2025-03-22T11:26:21Z"
             }
            """;

    public static final String GITHUB_USER_REPO_LIST_JSON = """
            [
               {
                 "id": 132935648,
                 "node_id": "MDEwOlJlcG9zaXRvcnkxMzI5MzU2NDg=",
                 "name": "boysenberry-repo-1",
                 "full_name": "octocat/boysenberry-repo-1",
                 "private": false,
                 "owner": {
                   "login": "octocat",
                   "id": 583231,
                   "node_id": "MDQ6VXNlcjU4MzIzMQ==",
                   "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/octocat",
                   "html_url": "https://github.com/octocat",
                   "followers_url": "https://api.github.com/users/octocat/followers",
                   "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                   "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                   "organizations_url": "https://api.github.com/users/octocat/orgs",
                   "repos_url": "https://api.github.com/users/octocat/repos",
                   "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/octocat/received_events",
                   "type": "User",
                   "user_view_type": "public",
                   "site_admin": false
                 },
                 "html_url": "https://github.com/octocat/boysenberry-repo-1",
                 "description": "Testing",
                 "fork": true,
                 "url": "https://api.github.com/repos/octocat/boysenberry-repo-1",
                 "forks_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/forks",
                 "keys_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/keys{/key_id}",
                 "collaborators_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/collaborators{/collaborator}",
                 "teams_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/teams",
                 "hooks_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/hooks",
                 "issue_events_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/issues/events{/number}",
                 "events_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/events",
                 "assignees_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/assignees{/user}",
                 "branches_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/branches{/branch}",
                 "tags_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/tags",
                 "blobs_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/git/blobs{/sha}",
                 "git_tags_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/git/tags{/sha}",
                 "git_refs_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/git/refs{/sha}",
                 "trees_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/git/trees{/sha}",
                 "statuses_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/statuses/{sha}",
                 "languages_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/languages",
                 "stargazers_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/stargazers",
                 "contributors_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/contributors",
                 "subscribers_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/subscribers",
                 "subscription_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/subscription",
                 "commits_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/commits{/sha}",
                 "git_commits_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/git/commits{/sha}",
                 "comments_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/comments{/number}",
                 "issue_comment_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/issues/comments{/number}",
                 "contents_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/contents/{+path}",
                 "compare_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/compare/{base}...{head}",
                 "merges_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/merges",
                 "archive_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/{archive_format}{/ref}",
                 "downloads_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/downloads",
                 "issues_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/issues{/number}",
                 "pulls_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/pulls{/number}",
                 "milestones_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/milestones{/number}",
                 "notifications_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/notifications{?since,all,participating}",
                 "labels_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/labels{/name}",
                 "releases_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/releases{/id}",
                 "deployments_url": "https://api.github.com/repos/octocat/boysenberry-repo-1/deployments",
                 "created_at": "2018-05-10T17:51:29Z",
                 "updated_at": "2025-03-21T15:17:58Z",
                 "pushed_at": "2024-05-26T07:02:05Z",
                 "git_url": "git://github.com/octocat/boysenberry-repo-1.git",
                 "ssh_url": "git@github.com:octocat/boysenberry-repo-1.git",
                 "clone_url": "https://github.com/octocat/boysenberry-repo-1.git",
                 "svn_url": "https://github.com/octocat/boysenberry-repo-1",
                 "homepage": "",
                 "size": 4,
                 "stargazers_count": 317,
                 "watchers_count": 317,
                 "language": null,
                 "has_issues": false,
                 "has_projects": true,
                 "has_downloads": true,
                 "has_wiki": true,
                 "has_pages": false,
                 "has_discussions": false,
                 "forks_count": 19,
                 "mirror_url": null,
                 "archived": false,
                 "disabled": false,
                 "open_issues_count": 1,
                 "license": null,
                 "allow_forking": true,
                 "is_template": false,
                 "web_commit_signoff_required": false,
                 "topics": [
             
                 ],
                 "visibility": "public",
                 "forks": 19,
                 "open_issues": 1,
                 "watchers": 317,
                 "default_branch": "master"
               },
               {
                 "id": 18221276,
                 "node_id": "MDEwOlJlcG9zaXRvcnkxODIyMTI3Ng==",
                 "name": "git-consortium",
                 "full_name": "octocat/git-consortium",
                 "private": false,
                 "owner": {
                   "login": "octocat",
                   "id": 583231,
                   "node_id": "MDQ6VXNlcjU4MzIzMQ==",
                   "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
                   "gravatar_id": "",
                   "url": "https://api.github.com/users/octocat",
                   "html_url": "https://github.com/octocat",
                   "followers_url": "https://api.github.com/users/octocat/followers",
                   "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                   "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                   "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                   "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                   "organizations_url": "https://api.github.com/users/octocat/orgs",
                   "repos_url": "https://api.github.com/users/octocat/repos",
                   "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                   "received_events_url": "https://api.github.com/users/octocat/received_events",
                   "type": "User",
                   "user_view_type": "public",
                   "site_admin": false
                 },
                 "html_url": "https://github.com/octocat/git-consortium",
                 "description": "This repo is for demonstration purposes only.",
                 "fork": false,
                 "url": "https://api.github.com/repos/octocat/git-consortium",
                 "forks_url": "https://api.github.com/repos/octocat/git-consortium/forks",
                 "keys_url": "https://api.github.com/repos/octocat/git-consortium/keys{/key_id}",
                 "collaborators_url": "https://api.github.com/repos/octocat/git-consortium/collaborators{/collaborator}",
                 "teams_url": "https://api.github.com/repos/octocat/git-consortium/teams",
                 "hooks_url": "https://api.github.com/repos/octocat/git-consortium/hooks",
                 "issue_events_url": "https://api.github.com/repos/octocat/git-consortium/issues/events{/number}",
                 "events_url": "https://api.github.com/repos/octocat/git-consortium/events",
                 "assignees_url": "https://api.github.com/repos/octocat/git-consortium/assignees{/user}",
                 "branches_url": "https://api.github.com/repos/octocat/git-consortium/branches{/branch}",
                 "tags_url": "https://api.github.com/repos/octocat/git-consortium/tags",
                 "blobs_url": "https://api.github.com/repos/octocat/git-consortium/git/blobs{/sha}",
                 "git_tags_url": "https://api.github.com/repos/octocat/git-consortium/git/tags{/sha}",
                 "git_refs_url": "https://api.github.com/repos/octocat/git-consortium/git/refs{/sha}",
                 "trees_url": "https://api.github.com/repos/octocat/git-consortium/git/trees{/sha}",
                 "statuses_url": "https://api.github.com/repos/octocat/git-consortium/statuses/{sha}",
                 "languages_url": "https://api.github.com/repos/octocat/git-consortium/languages",
                 "stargazers_url": "https://api.github.com/repos/octocat/git-consortium/stargazers",
                 "contributors_url": "https://api.github.com/repos/octocat/git-consortium/contributors",
                 "subscribers_url": "https://api.github.com/repos/octocat/git-consortium/subscribers",
                 "subscription_url": "https://api.github.com/repos/octocat/git-consortium/subscription",
                 "commits_url": "https://api.github.com/repos/octocat/git-consortium/commits{/sha}",
                 "git_commits_url": "https://api.github.com/repos/octocat/git-consortium/git/commits{/sha}",
                 "comments_url": "https://api.github.com/repos/octocat/git-consortium/comments{/number}",
                 "issue_comment_url": "https://api.github.com/repos/octocat/git-consortium/issues/comments{/number}",
                 "contents_url": "https://api.github.com/repos/octocat/git-consortium/contents/{+path}",
                 "compare_url": "https://api.github.com/repos/octocat/git-consortium/compare/{base}...{head}",
                 "merges_url": "https://api.github.com/repos/octocat/git-consortium/merges",
                 "archive_url": "https://api.github.com/repos/octocat/git-consortium/{archive_format}{/ref}",
                 "downloads_url": "https://api.github.com/repos/octocat/git-consortium/downloads",
                 "issues_url": "https://api.github.com/repos/octocat/git-consortium/issues{/number}",
                 "pulls_url": "https://api.github.com/repos/octocat/git-consortium/pulls{/number}",
                 "milestones_url": "https://api.github.com/repos/octocat/git-consortium/milestones{/number}",
                 "notifications_url": "https://api.github.com/repos/octocat/git-consortium/notifications{?since,all,participating}",
                 "labels_url": "https://api.github.com/repos/octocat/git-consortium/labels{/name}",
                 "releases_url": "https://api.github.com/repos/octocat/git-consortium/releases{/id}",
                 "deployments_url": "https://api.github.com/repos/octocat/git-consortium/deployments",
                 "created_at": "2014-03-28T17:55:38Z",
                 "updated_at": "2025-03-19T06:32:28Z",
                 "pushed_at": "2024-07-12T15:04:33Z",
                 "git_url": "git://github.com/octocat/git-consortium.git",
                 "ssh_url": "git@github.com:octocat/git-consortium.git",
                 "clone_url": "https://github.com/octocat/git-consortium.git",
                 "svn_url": "https://github.com/octocat/git-consortium",
                 "homepage": null,
                 "size": 190,
                 "stargazers_count": 407,
                 "watchers_count": 407,
                 "language": null,
                 "has_issues": true,
                 "has_projects": true,
                 "has_downloads": true,
                 "has_wiki": true,
                 "has_pages": false,
                 "has_discussions": false,
                 "forks_count": 110,
                 "mirror_url": null,
                 "archived": false,
                 "disabled": false,
                 "open_issues_count": 44,
                 "license": {
                   "key": "mit",
                   "name": "MIT License",
                   "spdx_id": "MIT",
                   "url": "https://api.github.com/licenses/mit",
                   "node_id": "MDc6TGljZW5zZTEz"
                 },
                 "allow_forking": true,
                 "is_template": false,
                 "web_commit_signoff_required": false,
                 "topics": [
             
                 ],
                 "visibility": "public",
                 "forks": 110,
                 "open_issues": 44,
                 "watchers": 407,
                 "default_branch": "master"
               }
             ]
            """;

    public static final String APPLICATION_GITHUB_USER_RESPONSE = """
            {
                "user_name": "octocat",
                "display_name": "The Octocat",
                "avatar": "https://avatars.githubusercontent.com/u/583231?v=4",
                "geo_location": "San Francisco",
                "email": null,
                "url": "https://github.com/octocat",
                "created_at": "2011-01-25 18:44:36",
                "repos": [
                    {
                        "name": "boysenberry-repo-1",
                        "url": "https://github.com/octocat/boysenberry-repo-1"
                    },
                    {
                        "name": "git-consortium",
                        "url": "https://github.com/octocat/git-consortium"
                    },
                    {
                        "name": "hello-worId",
                        "url": "https://github.com/octocat/hello-worId"
                    },
                    {
                        "name": "Hello-World",
                        "url": "https://github.com/octocat/Hello-World"
                    },
                    {
                        "name": "linguist",
                        "url": "https://github.com/octocat/linguist"
                    },
                    {
                        "name": "octocat.github.io",
                        "url": "https://github.com/octocat/octocat.github.io"
                    },
                    {
                        "name": "Spoon-Knife",
                        "url": "https://github.com/octocat/Spoon-Knife"
                    },
                    {
                        "name": "test-repo1",
                        "url": "https://github.com/octocat/test-repo1"
                    }
                ]
            }
            """;
}
